### PR TITLE
Use separate variables for the height and stride

### PR DESCRIPTION
**Pull request by kekrby**

### CODE REVIEW

**Comment by WhatAmISupposedToPutHere** [comment]
NAK, this breaks m1

**Comment by kekrby** [comment]
How does this break M1s? According to https://github.com/AsahiLinux/m1n1/blob/main/proxyclient/experiments/touchbar_rainbow.py#L13, the height of the Touch Bar displays on M1s are 60.

**Comment by WhatAmISupposedToPutHere** [comment]
The line stride is 64, and using 60 as height turns the image into cut up lines.

**Comment by kekrby** [comment]
I added a separate variable for the stride. Can you check if it works on M1s?

**Comment by WhatAmISupposedToPutHere** [comment]
Results in misaligned buttons on m1.
IMG_0496

**Comment by kekrby** [comment]
Can you test the new version please?

**Comment by kekrby** [comment]
Can you test the new version?

**Comment by WhatAmISupposedToPutHere** [comment]
Well, it doesn't even compile, :P But even after i fixed the compile error, the labels are still misaligned.

**Comment by kekrby** [comment]
> Well, it doesn't even compile, :P

Sorry about that, I forgot to amend the fix after adding it.

Could you please test it again?

**Comment by WhatAmISupposedToPutHere** [comment]
I have noticed that you haven't actually did anything to the label drawing code so they will still be misaligned. Git pilot error? :P

**Comment by kekrby** [comment]
I changed the `x2` value of the rectangle passed to `drm.dirty` from `DFR_HEIGHT` to `DFR_STRIDE`, since I guessed that it could possibly be the cause.

**Comment by WhatAmISupposedToPutHere** [comment]
Nope, that call just flushes the pixels from memory to the display controller. (The exact arguments don't even matter on m1, the driver does not do damage tracking and always sends a full screen frame)

**Comment by kekrby** [comment]
I thought that the issue could be caused by the top 4 pixels not being flushed as the buttons get cut off on my Touch Bar too if I decrease `x2` by 4.

**Comment by kekrby** [comment]
Turns out that I can replicate the setup on M1s if I create a dumb buffer with a with of 64. I think this version should work :).

**Comment by kekrby** [comment]
Turns out that I can replicate the setup on M1s if I create a dumb buffer with a width of 64. I think this version should work :).

**Pull request merged**
