### PR TITLE
Visual improvements

### PR DESCRIPTION
**Pull request by kekrby**
These changes bring the overall look closer to macOS, which is what most people are used to

### CODE REVIEW

**Comment by kekrby** [comment]
The icons are from the rounded and filled variant of the Google Material Symbols icon set, with the exception of the play/pause icon, which is the play and pause icons combined in Inkscape.

I'll drop the font weight change.

**Comment by WhatAmISupposedToPutHere** [comment]
Was it you specifically who made the play/pause icon, or someone else?

**Comment by kekrby** [comment]
I made the icon

**Comment by WhatAmISupposedToPutHere** [comment]
Merged manually. I ended up tweaking the icon heights myself, they were being cut off on M1 MBP

**Pull request closed without merging**
