### PR TITLE
Redraw only the buttons whose states changed and provide damage information to the kernel

### PR DESCRIPTION
**Pull request by kekrby**

### CODE REVIEW

**Comment by WhatAmISupposedToPutHere** [comment]
Merged manually

**Comment by kekrby** [comment]
Why did you drop the changes related to copying? Also, it looks like you didn't remove `fb_info`, which is unused now.

**Comment by WhatAmISupposedToPutHere** [comment]
Those were resulting in weird rendering on m1.

**Comment by kekrby** [comment]
> Also, it looks like you didn't remove fb_info, which is unused now.

I opened #19 for that

**Pull request closed without merging**
